name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: debian:trixie
      options: --privileged

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies (minimal build) 
      run: apt update
    - name: Instalar dependências básicas
      run: apt install -y build-essential autoconf libssl-dev
    - name: prepare autoconf
      run: autoreconf -if 
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: install dependencies (full build)
      run: apt update
    - name: all dependencies
      run: apt install -y libpq5 libpq-dev libssh2-1 libssh2-1-dev libgnutls28-dev libsvn-dev libsmb2-dev
    - name: configure
      run: ./configure --disable-module-smbnt --enable-module-smbnt-smb2
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
