name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: debian:trixie
      options: --privileged

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies (minimal build) 
      run: apt-get update -y
    - name: Instalar dependências básicas
      run: apt-get install -y \
           build-essential \
           autoconf \
           automake \
           libtool \
           libssl-dev \
           git
    - name: prepare autoconf
      run: autoreconf -if 
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: install dependencies (full build)
      run: |
           apt-get update -y
    - name: all dependencies
      run: apt-get install -y \
           libpq5 \
           libpq-dev \
           libssh2-1 \
           libssh2-1-dev \
           libgnutls28-dev \
           libsvn-dev \
           freerdp2-dev \
           libsmb2-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
